export const trending = (req, res) => res.render("home")
export const see = (req, res) => res.render("watch")
export const edit = (req, res) => res.render("edit")
export const Search = (req, res) => res.send("Search Videos")
export const Upload = (req, res) => res.send("Upload Video")
export const Delete = (req, res) => res.send("Delete Video")